### ISSUE TITLE
Visualising the output

### ISSUE THREAD

**Issue by yassineS** [AI-sandbox/archetypal-analysis#2]
Hello,

It will be greate if you could kindly provide a guide on how to visualise the AA analysis once the Q/Z files are produced. I noticed that there's a number of plottin functions in the [archetypal_analysis](https://github.com/AI-sandbox/archetypal-analysis/tree/55e7f19052f210524046f6f5c0b16657254e99cd/archetypal_analysis)/[src](https://github.com/AI-sandbox/archetypal-analysis/tree/55e7f19052f210524046f6f5c0b16657254e99cd/archetypal_analysis/src)/archetypal_analysis.py file, but no clear way of accessing the functions or how to use Q/Z files to generate a plot.

Many thanks!
Y

**Comment by dralhindi** [comment]
Hi everyone, 

I second this. Some guidelines or an example would be incredibly useful. 

Many thanks, 
D

**Comment by nitinra** [comment]
Just checking in to see if there is any update on guideline to visualize the Q/Z files! TIA!

**Comment by avahoffman** [comment]
Also chiming in to say it would be great to get the code for the polygon plots. Thanks!!

**Comment by yassineS** [comment]
This issue has been resolved since the authors provide now a full plotting functionality: https://github.com/AI-sandbox/archetypal-analysis/blob/master/README.md#plotting
